language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq avahi-daemon libavahi-compat-libdnssd-dev
  - sudo insserv avahi-daemon
